apps/pages/urls.py
from django.urls import path
from . import views
from django.urls import path, re_path


app_name = 'pages'

urlpatterns = [
    path('', views.contentView, name='home'),
    path('<slug:slug>/', views.contentView, name='page'),


]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('apps.pages.urls')),
    path('', include('apps.pages.urls')),
    path('news/', include('apps.news.urls')),
    #path('pages/', include('apps.pages.urls')),
   # path('pages/', include('apps.pages.urls')),
   # path('pages/', include('apps.pages.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_footer.html
{% load static %}


  <!-- ======= Footer ======= -->
  <footer>
    <div class="footer-area" >
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="footer-content">
              <div class="footer-head">
                <div class="footer-logo">
                  <h2><span>e</span>Business</h2>
                </div>
                  <p>This project has been funded with support from the
                    European Commission under the Erasmus+ Programme.
                    This publication reflects the views only of the author,
                    and the Commission cannot be held responsible for any
                    use which may be made of the information contained
                    therein</p>

                <div class="footer-icons">
                  <ul>
                    <li>
                       <a href="https://www.facebook.com/cemal.kutlu.7906" target="_blank" class="facebook"><i class="bx bxl-facebook"></i></a>
                    </li>
                    <li>
                      <a href="https://twitter.com/08mart1993" target="_blank"  class="twitter"><i class="bx bxl-twitter"></i></a>
                    </li>
                    <li>
                      <a href="https://www.linkedin.com/in/tek-sav-vakfi-a73018156/" target="_blank" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <!-- end single footer -->
          <div class="col-md-4">
            <div class="footer-content">
              <div class="footer-head">
                <h4>Tekniker Eğitim Kültür Sağlık Vakfı (TEK-SAV)</h4>
                <p>
                  Şehit Çetin Görgü Sokak, No: 09 / 10 Maltepe 06570 <br>
                  Çankaya / Ankara<br>
                  Türkiye <br><br>
                  <strong>Phone:</strong> 0532 344 0 257 (Cemal Kutlu)<br>
                  <strong>Email:</strong> teksavinfo@gmail.com<br>
                </p>
              </div>
            </div>
          </div>
          <!-- end single footer -->
          <div class="col-md-4">
            <div class="footer-content">
              <div class="footer-head">
                  <a class="logo me-auto me-lg-0"><img src="{% static 'assets/img/Flag_of_Europe.png' %}" alt="" class="img-fluid" style='max-height:75%; margin-bottom:15px;'></a>
                  <h4>Funded by The 
                    European Union<h4/>
                  <p>Project No : 101086205 ( 2023-2025)
                    ERASMUS YOUTH-2022-YOUTH-TOG</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-area-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="copyright text-center">
              <p>
                &copy; Copyright <strong>eBusiness</strong>. All Rights Reserved
              </p>
            </div>
            <div class="credits">
              <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=eBusiness
            -->
              Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/partials/_header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Let Us Think Green</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/letusLogo.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">


  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


</head>

templates/partials/_menu.html
{% load static %}


  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between">

      <div class="logo me-lg-0">
        <h1><a href="index.html"><img src="{% static 'assets/img/letusLogo.png' %}"  alt="" class="img-fluid"><span>Let Us Think </span>Green</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
         <!--<a href="index.html"><img src="{% static 'assets/img/letusLogo.jpg' %}"  alt="" class="img-fluid"></a> -->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          {% for item in menu_list %}
          {% if item.parent_id is None and item.IsClickable is not True %}
            <li class="dropdown"><a href="{% url 'pages:page' item.Slug %}" onclick="return false"><span>{{item.PageTitle}}</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                {% for subitem in menu_list  %}
                  {% if item.id == subitem.parent_id %}
                    <li><a href="{% url 'pages:page' subitem.Slug %}">{{subitem.PageTitle}}</a></li>
                  {% endif %}
                {% endfor %}
              </ul>
          {% endif %}
          {% if item.parent_id is None and item.IsClickable is  True %}
          <li class="dropdown"><a href="{% url 'pages:page' item.Slug %}" ><span>{{item.PageTitle}}</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              {% for subitem in menu_list  %}
                {% if item.id == subitem.parent_id %}
                  <li><a href="{% url 'pages:page' subitem.Slug %}">{{subitem.PageTitle}}</a></li>
                {% endif %}
              {% endfor %}
            </ul>
          {% endif %}
          {% endfor %}
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      {% comment %} <div class="logo me-rg-0">
        <!-- Uncomment below if you prefer to use an image logo -->
        <a href="index.html"><img src="{% static 'assets/img/teksav_logo.jpg' %}"  alt="" class="img-fluid"></a> 
      </div> {% endcomment %}
    </div>
  </header><!-- End Header -->